### PR TITLE
Handle getObject for primitives properly

### LINKED ISSUE #789: "Invalid remote object id" when calling getObject for bools
This seems similar to https://github.com/dart-lang/webdev/issues/773 but for bools. A boolean variable is returned with the ID `objects/bool-true`:

```js
"value": {
	"type": "@Instance",
	"id": "objects/bool-true",
	"kind": "Bool",
	"class": {
		"type": "@Class",
		"id": "classes|dart:core|Bool",
		"name": "Bool"
	},
	"valueAsString": "true",
	"valueAsStringIsTruncated": false
}
```

But calls to `getObject` with that ID fail:

```
==> {"id":"503","method":"getObject","params":{"isolateId":"1","objectId":"objects/bool-true"}}
```

```
{
	"jsonrpc": "2.0",
	"error": {
		"code": -32603,
		"message": "
			WipError 1572: {code: -32000, message: Invalid remote object id}
			#0      AppInspector.jsCallFunctionOn (package:dwds/src/debugging/inspector.dart:183:9)
			<asynchronous suspension>
			#1      ClassMetaData.metaDataFor (package:dwds/src/debugging/metadata.dart:65:36)
			<asynchronous suspension>
			#2      InstanceHelper.instanceFor (package:dwds/src/debugging/instance.dart:52:40)
			<asynchronous suspension>
			#3      AppInspector.getObject (package:dwds/src/debugging/inspector.dart:313:24)
			<asynchronous suspension>
			#4      ChromeProxyService.getObject (package:dwds/src/services/chrome_proxy_service.dart:311:19)
			#5      VmServerConnection._delegateRequest (package:vm_service/vm_service.dart:1027:51)
			<asynchronous suspension>
			#6      _rootRunUnary (dart:async/zone.dart:1132:38)
			#7      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
			#8      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
		"
	},
	"id": "503"
}
```

### PR DESCRIPTION
**Pull request by alan-knight**
Closes #789

### CODE REVIEW

File: dwds/lib/src/utilities/conversions.dart [hunk 1]
```diff
@@ -18,14 +18,20 @@ import 'package:webkit_inspection_protocol/webkit_inspection_protocol.dart';
...
+    return isPrimitive(argument)
         ? _callArgumentForPrimitive(argument.value)
         : _callArgumentForRemote(argument);
   } else {
     return _callArgumentForPrimitive(argument);
   }
 }
 
+/// True if [remote] represents a primitive
+bool isPrimitive(RemoteObject remote) {
```
Comment (grouma) [inline dwds/lib/src/utilities/conversions.dart]: Private?

Comment (alan-knight) [reply dwds/lib/src/utilities/conversions.dart]: Done.
