### PR TITLE
Fix two null errors in toJson of vm protocol objects

### LINKED ISSUE #690: NoSuchMethodError: The method 'toJson' was called on null
With the Flutter tool on dwds 0.6.2, from crash logging with backtrace:

```
NoSuchMethodError: The method 'toJson' was called on null.
Receiver: null
Tried calling: toJson()
  | at Object.noSuchMethod | (object_patch.dart:51 )
  | at SourceLocation.toJson | (vm_service.dart:5306 )
  | at Frame.toJson | (vm_service.dart:3501 )
  | at Event.toJson | (vm_service.dart:3227 )
  | at VmServerConnection._delegateRequest.<anonymous closure> | (vm_service.dart:1174 )
  | at _rootRunUnary | (zone.dart:1132 )
  | at _CustomZone.runUnary | (zone.dart:1029 )
  | at _CustomZone.runUnaryGuarded | (zone.dart:931 )
  | at _BufferingStreamSubscription._sendData | (stream_impl.dart:336 )
  | at _DelayedData.perform | (stream_impl.dart:591 )
  | at _StreamImplEvents.handleNext | (stream_impl.dart:707 )
  | at _PendingEvents.schedule.<anonymous closure> | (stream_impl.dart:667 )
  | at _rootRun | (zone.dart:1120 )
  | at _CustomZone.run | (zone.dart:1021 )
  | at _CustomZone.runGuarded | (zone.dart:923 )
  | at _CustomZone.bindCallbackGuarded.<anonymous closure> | (zone.dart:963 )
  | at _rootRun | (zone.dart:1124 )
  | at _CustomZone.run | (zone.dart:1021 )
  | at _CustomZone.runGuarded | (zone.dart:923 )
  | at _CustomZone.bindCallbackGuarded.<anonymous closure> | (zone.dart:963 )
  | at _microtaskLoop | (schedule_microtask.dart:41 )
  | at _startMicrotaskLoop | (schedule_microtask.dart:50 )
  | at _runPendingImmediateCallback | (isolate_patch.dart:116 )
  | at _RawReceivePortImpl._handleMessage | (isolate_patch.dart:173 )
```

This is the most frequent crasher that we're currently seeing from the Flutter tool overall on master and dev.

/cc @jakemac53

### PR DESCRIPTION
**Pull request by alan-knight**
Fixes #690

### CODE REVIEW

File: dwds/lib/src/debugging/debugger.dart [hunk 1]
```diff
@@ -390,6 +390,10 @@ class Debugger extends Domain {
     if (bestLocation == null) return null;
     var script =
         await inspector?.scriptRefFor(bestLocation.dartLocation.uri.serverPath);
+    // We think we found a location, but for some reason we can't find the script.
+    // Just drop the frame.
+    // TODO: Understand when this can happen and have a better fix.
```
Comment (jakemac53) [inline dwds/lib/src/debugging/debugger.dart]: possibly inspector was null?

Comment (alan-knight) [reply dwds/lib/src/debugging/debugger.dart]: Added a bug ( #700 ) . That could be the reason, in which case we're going to end up dropping all the frames, which is not that much better than crashing. But it could also be other problems with our source logic.
