### PR TITLE
Wrap a zone exception handler around our Chrome event handlers

### LINKED ISSUE #730: Handle errors in our event handlers

### PR DESCRIPTION
**Pull request by alan-knight**
Fixes #730

### CODE REVIEW

File: dwds/test/debugger_test.dart [hunk 1]
```diff
@@ -65,4 +72,20 @@ void main() async {
...
+
+  group('errors', () {
+    setUp(() {
+      // We need to provide an Isolate so that the code doesn't bail out on a null
+      // check before it has a chance to throw.
+      inspector = FakeInspector(fakeIsolate: simpleIsolate);
+    });
+
+    test('errors in the zone are caught and logged', () async {
+      var debug = logging.Logger('Debug');
```
Comment (jakemac53) [inline dwds/test/debugger_test.dart]: This should be `Debugger` I thought? It might be best to just expose the logger that library uses publicly instead of copying the name. Or you can do `logging.Logger.root` but you might see other logs in that case.

In general it is probably best to do an `emitsThrough` check here anyways:

```
expect(debug.onRecord, emitsThrough(predicate((log) => log.message == 'Error handling Chrome event)));
```

That way it will not get flaky/broken if other messages are added.

Comment (alan-knight) [reply dwds/test/debugger_test.dart]: Made Debugger.logger public and used that, and also changed to use emitThrough.
